/* CPU-only Phase 2a contract harness. Transaction cases use real storage. */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include "msxresident_core.h"
#include "msxresident_hash.h"
#include "msxsegment_storage.h"
#include "msxresident_runtime.h"
#include "msxgpu.h"
#include "msxtypes.h"
MSXproject MSX; static int pass,fail; static int segmentAllocFail; static uint64_t segmentAllocCalls;
#define OK(x) do{if(x)pass++;else{fail++;fprintf(stderr,"FAIL:%s:%d: %s\n",__FILE__,__LINE__,#x);}}while(0)
int ENgetlinkid(int i,char*id){sprintf(id,"L%d",i);return 0;} int ENwriteline(char*s){(void)s;return 0;}
char *Alloc(long n){return(char*)calloc(1,(size_t)n);} double MSXgpu_wallTimeMs(void){return 0.0;}
/* The standalone CPU harness does not link msxgpu.c.  Keep the stage gate
   disabled here; production builds resolve it from the GPU timing module. */
int MSXgpu_profileStageEnabled(void){return 0;}
int MSXgpu_profileDetailGroupEnabled(MSXProfileDetailGroup group){(void)group;return 0;}
void MSXgpu_profileRecordDemote(uint64_t rows,double ms){(void)rows;(void)ms;}
void MSXgpu_profileRecordPromote(uint64_t rows,double ms){(void)rows;(void)ms;}
void MSXgpu_profileRecordRebalance(const MSXRebalanceMetrics *metrics){(void)metrics;}
Pseg MSXqual_getFreeSeg(double v,double*c){Pseg s;int n=MSX.Nobjects[SPECIES]+1;segmentAllocCalls++;if(segmentAllocFail)return NULL;s=(Pseg)calloc(1,sizeof(*s));if(!s)return NULL;s->c=(double*)calloc(n,sizeof(double));s->lastc=(double*)calloc(n,sizeof(double));if(!s->c||!s->lastc){free(s->c);free(s->lastc);free(s);return NULL;}s->privateC=s->c;s->privateLastC=s->lastc;s->v=v;if(c)memcpy(s->c,c,n*sizeof(double));return s;}
void MSXqual_removeSeg(Pseg s){if(!s)return;if(MSXsegStorage_hybridReleaseBoundary(s))return;free(s->privateC);if(s->privateLastC!=s->privateC)free(s->privateLastC);free(s);}
static void csv(const char*n,const char*b){FILE*f=fopen(n,"wb");if(f){fputs(b,f);fclose(f);}}
static void cleanup(void){int k;MSXresident_close();if(MSX.FirstSeg)for(k=1;k<=MSX.Nobjects[LINK];k++){Pseg s=MSX.FirstSeg[k],q;while(s){q=s->prev;if(!s->inHybridCore)MSXqual_removeSeg(s);s=q;}}MSXsegStorage_close();free(MSX.FirstSeg);free(MSX.LastSeg);free(MSX.Link);memset(&MSX,0,sizeof(MSX));}
static void setup(int species,int links){cleanup();MSX.Nobjects[LINK]=links;MSX.Nobjects[SPECIES]=species;MSX.MaxSegments=16;MSX.SegmentStorage=SEG_STORAGE_PSEG;MSX.Link=(Slink*)calloc(links+1,sizeof(Slink));MSX.FirstSeg=(Pseg*)calloc(links+1,sizeof(Pseg));MSX.LastSeg=(Pseg*)calloc(links+1,sizeof(Pseg));}
static MSXResidentPayload payload(double*c,double*l,double v,uint64_t id){MSXResidentPayload p;memset(&p,0,sizeof(p));p.volume=v;p.hstep=7;p.hresponse=8;p.uresponse=9;p.dresponse=10;p.parcelId=id;p.c=c;p.lastc=l;return p;}
static void open1(const char*b){csv("resident_phase2a.csv",b);OK(MSXresident_open("resident_phase2a.csv")==0);MSXresident_setMode(MSX_RESIDENT_SHADOW,0);}
static void onecsv(char*b,size_t z,const char*h,uint32_t cap){snprintf(b,z,"link_index,link_id,capacity,max_core_count,combined_burst_p99,guard,case_hash\n1,L1,%u,%u,1,2,%s\n",cap,cap,h);}
static const char*UP="ABCDEFABCDEFABCDEFABCDEFABCDEFABCDEFABCDEFABCDEFABCDEFABCDEFABCD";static const char*LO="abcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcdefabcd";
/* 1: CSV/hash contract. */
static void t1(void){char b[512];setup(1,1);onecsv(b,sizeof(b),LO,2);open1(b);OK(MSXresident_verifyCaseHash(UP)==0);OK(MSXresident_verifyCaseHash(LO)==0);OK(MSXresident_verifyCaseHash("abcdef")==MSX_RESIDENT_ERR_CASE_HASH);MSXresident_close();onecsv(b,sizeof(b),UP,2);b[strlen(b)-3]='G';csv("resident_phase2a.csv",b);OK(MSXresident_open("resident_phase2a.csv")==MSX_RESIDENT_ERR_CSV);}
/* 2: payload row layout. */
static void t2(void){int n;char b[512];for(n=1;n<=3;n++){double c[4]={0,11,12,13},l[4]={0,21,22,23};uint64_t id=44;MSXResidentPayload p,q;setup(n,1);onecsv(b,sizeof(b),UP,2);open1(b);p=payload(c,l,1.5,id);OK(MSXresident_observePipe(1,&id,&p,1,1)==0);OK(MSXresident_getSlotPayload(1,0,1,&q)==0);OK(q.c!=q.lastc&&q.c[n]==c[n]&&q.lastc[n]==l[n]);}}
/* 3: descriptor/slot patch publication. */
static void t3(void){char b[512];double c[2]={0,1},l[2]={0,2};uint64_t id=10;MSXResidentPayload p=payload(c,l,2,id);MSXResidentPatchBatch x;setup(1,1);onecsv(b,sizeof(b),UP,3);open1(b);OK(MSXresident_observePipe(1,&id,&p,1,1)==0);OK(MSXresident_getPatches(&x)==0&&x.descriptorCount==1&&x.slotCount==1&&x.slot[0].used==1);MSXresident_clearPatches();OK(MSXresident_getPatches(&x)==0&&x.descriptorCount==0&&x.slotCount==0);}
/* 4: duplicate preflight is atomic. */
static void t4(void){char b[512];double c[2]={0,1},l[2]={0,2};uint64_t ids[2]={10,20};MSXResidentPayload p[2],q;setup(1,1);onecsv(b,sizeof(b),UP,2);open1(b);p[0]=payload(c,l,2,10);p[1]=payload(c,l,3,20);OK(MSXresident_observePipe(1,ids,p,2,1)==0);ids[1]=10;OK(MSXresident_observePipe(1,ids,p,2,1)==MSX_RESIDENT_ERR_ARGUMENT);OK(MSXresident_getSlotPayload(1,1,1,&q)==0&&q.parcelId==20);}
/* 5: released slot generations. */
static void t5(void){char b[512];double c[2]={0,1},l[2]={0,2};uint64_t id=10;MSXResidentPayload p=payload(c,l,2,id),q;setup(1,1);onecsv(b,sizeof(b),UP,1);open1(b);OK(MSXresident_observePipe(1,&id,&p,1,1)==0);OK(MSXresident_observePipe(1,NULL,NULL,0,1)==0);id=20;p.parcelId=id;OK(MSXresident_observePipe(1,&id,&p,1,1)==0);OK(MSXresident_getSlotPayload(1,0,1,&q)==MSX_RESIDENT_ERR_GENERATION);OK(MSXresident_getSlotPayload(1,0,2,&q)==0&&q.parcelId==20);}
/* 6: plan boundary/capacity behavior. */
static void t6(void){char b[512];double c[2]={0,1},l[2]={0,2};uint64_t ids[2]={10,20};MSXResidentPayload p[2];MSXResidentHandoffPlan q;setup(1,1);onecsv(b,sizeof(b),UP,2);open1(b);p[0]=payload(c,l,2,10);p[1]=payload(c,l,3,20);OK(MSXresident_observePipe(1,ids,p,2,1)==0);OK(MSXresident_planHandoff(1,2,1,0,2,1,&q)==0&&q.itemCount==0);OK(MSXresident_planHandoff(1,4,1,0,0,1,&q)==0&&q.itemCount==2&&q.item[0].requestedVolume==2);OK(MSXresident_planHandoff(1,9,1,0,0,0,&q)==MSX_RESIDENT_FALLBACK_WHOLE_LINK);}
/* 6a: runtime caps Q*dt to LINKVOL before strict handoff planning.  A raw
   displacement larger than the pipe volume therefore requests each resident
   slot exactly once, while an ordinary displacement keeps its old plan. */
static void t6a(void){char b[512];double c[2]={0,1},l[2]={0,2};uint64_t ids[2]={10,20};MSXResidentPayload p[2];MSXResidentHandoffItem item[2];MSXResidentHandoffPlan q;double linkvol=0.785398*10.0*2.0*2.0,raw,displacement;setup(1,1);onecsv(b,sizeof(b),UP,2);open1(b);p[0]=payload(c,l,10.0,10);p[1]=payload(c,l,10.0,20);OK(MSXresident_observePipe(1,ids,p,2,1)==0);raw=linkvol*2.0;displacement=(raw>linkvol)?linkvol:raw;OK(raw>linkvol&&displacement==linkvol&&MSXresident_planHandoffInto(1,displacement,1.0,0,0.0,1,item,2,&q)==MSX_RESIDENT_ERR_CAPACITY);OK(MSXresident_planAllHandoffInto(1,0,item,2,&q)==0&&q.itemCount==2);OK(MSXresident_planHandoffInto(1,10.0,1.0,0,0.0,1,item,2,&q)==0&&q.itemCount==1&&q.flowVolume==10.0);}
/* 6b: same-batch release/reuse publishes only final uploads. */
static void t6b(void){char b[512];double c[2]={0,1},l[2]={0,2};uint64_t a[2]={10,20},q[2]={30,20},both[2]={30,40};MSXResidentPayload p[2],check;MSXResidentPatchBatch x;uint32_t old10,old20,new30,i,uploads,invalidates,reuseUploads;setup(1,1);onecsv(b,sizeof(b),UP,2);open1(b);p[0]=payload(c,l,2,10);p[1]=payload(c,l,3,20);OK(MSXresident_observePipe(1,a,p,2,1)==0);old10=old20=UINT32_MAX;OK(MSXresident_getPatches(&x)==0);for(i=0;i<x.slotCount;i++){if(x.slot[i].payload.parcelId==10)old10=x.slot[i].slot;if(x.slot[i].payload.parcelId==20)old20=x.slot[i].slot;}OK(old10!=UINT32_MAX&&old20!=UINT32_MAX&&old10!=old20);MSXresident_clearPatches();p[0]=payload(c,l,4,30);p[1]=payload(c,l,3,20);OK(MSXresident_observePipe(1,q,p,2,1)==0);OK(MSXresident_getPatches(&x)==0&&x.descriptorCount==0&&x.slotCount==1);new30=UINT32_MAX;uploads=invalidates=reuseUploads=0;for(i=0;i<x.slotCount;i++){if(x.slot[i].used)uploads++;else invalidates++;if(x.slot[i].payload.parcelId==30)new30=x.slot[i].slot;if(x.slot[i].slot==old10&&x.slot[i].used)reuseUploads++;}OK(new30==old10&&reuseUploads==1&&uploads==1&&invalidates==0&&x.slot[0].generation==2&&x.slot[0].kind==MSX_RESIDENT_PATCH_IMPORT);OK(MSXresident_getSlotPayload(1,old20,1,&check)==0&&check.parcelId==20);setup(1,1);onecsv(b,sizeof(b),UP,2);open1(b);p[0]=payload(c,l,2,10);p[1]=payload(c,l,3,20);OK(MSXresident_observePipe(1,a,p,2,1)==0);MSXresident_clearPatches();p[0]=payload(c,l,4,30);p[1]=payload(c,l,5,40);OK(MSXresident_observePipe(1,both,p,2,1)==0);OK(MSXresident_getPatches(&x)==0&&x.descriptorCount==0&&x.slotCount==2);uploads=invalidates=0;for(i=0;i<x.slotCount;i++){if(x.slot[i].used)uploads++;else invalidates++;}OK(uploads==2&&invalidates==0&&x.slot[0].slot!=x.slot[1].slot&&x.slot[0].generation==2&&x.slot[1].generation==2);}
/* 6c: after open, observe/reverse/reuse is allocation-free even when the
   module allocation seam is armed to fail. */
static void t6c(void){char b[512];double c[2]={0,1},l[2]={0,2};uint64_t a[2]={10,20},q[2]={30,20};MSXResidentPayload p[2],x;MSXResidentPatchBatch patches;uint64_t n;setup(1,1);onecsv(b,sizeof(b),UP,2);open1(b);p[0]=payload(c,l,2,10);p[1]=payload(c,l,3,20);MSXresident_testResetAllocationCount();MSXresident_testFailAllocationAfter(0);OK(MSXresident_observePipe(1,a,p,2,1)==0);n=MSXresident_testAllocationCount();OK(n==0);OK(MSXresident_observePipe(1,a,p,2,-1)==0);OK(MSXresident_testAllocationCount()==n);MSXresident_clearPatches();p[0]=payload(c,l,4,30);p[1]=payload(c,l,3,20);OK(MSXresident_observePipe(1,q,p,2,-1)==0);OK(MSXresident_testAllocationCount()==n);OK(MSXresident_getPatches(&patches)==0&&patches.slotCount==1&&patches.slot[0].kind==MSX_RESIDENT_PATCH_IMPORT);OK(MSXresident_getSlotPayload(1,0,2,&x)==0&&x.parcelId==30);OK(MSXresident_getSlotPayload(1,1,1,&x)==0&&x.parcelId==20);MSXresident_testFailAllocationAfter(-1);}
/* 6d: observer preserves surviving slots across identity/orientation moves. */
static void t6d(void){char b[512];double c[2]={0,1},l[2]={0,2};uint64_t a[2]={10,20},q[2]={30,20},n;MSXResidentPayload p[2],x;MSXResidentPatchBatch z;uint32_t i,up=0,off=0;setup(1,1);onecsv(b,sizeof(b),UP,4);open1(b);p[0]=payload(c,l,2,10);p[1]=payload(c,l,3,20);MSXresident_testResetAllocationCount();MSXresident_testFailAllocationAfter(0);OK(MSXresident_observePipe(1,a,p,2,1)==0);n=MSXresident_testAllocationCount();MSXresident_clearPatches();p[0]=payload(c,l,4,30);p[1]=payload(c,l,3,20);OK(MSXresident_observePipe(1,q,p,2,-1)==0);OK(MSXresident_testAllocationCount()==n);OK(MSXresident_getPatches(&z)==0);OK(z.descriptorCount==1);OK(z.slotCount==2);OK(z.descriptor[0].descriptor.head==2&&z.descriptor[0].descriptor.tail==1&&z.descriptor[0].descriptor.count==2&&z.descriptor[0].descriptor.orient==-1);for(i=0;i<z.slotCount;i++){up+=z.slot[i].used;off+=!z.slot[i].used;}OK(up==1&&off==1);OK(MSXresident_getSlotPayload(1,2,1,&x)==0&&x.parcelId==30);OK(MSXresident_getSlotPayload(1,1,1,&x)==0&&x.parcelId==20);OK(MSXresident_getSlotPayload(1,0,1,&x)==MSX_RESIDENT_ERR_GENERATION);MSXresident_testFailAllocationAfter(-1);}
/* 6e: stable slots, typed incremental events, final-state patch merge, and
   touched-only clearing. */
static void t6e(void){char b[512];double c[2]={0,1},l[2]={0,2};uint64_t ids[2]={11,22};MSXResidentPayload p[2],m;MSXResidentPatchBatch x;MSXResidentPayload q;uint32_t s0,s1,g0,g1;uint64_t epoch;setup(1,1);onecsv(b,sizeof(b),UP,4);open1(b);p[0]=payload(c,l,2,11);p[1]=payload(c,l,3,22);OK(MSXresident_observePipe(1,ids,p,2,1)==0);OK(MSXresident_getSlotForParcel(1,11,&s0,&g0)==0&&MSXresident_getSlotForParcel(1,22,&s1,&g1)==0&&s0==0&&s1==1&&g0==1&&g1==1);OK(MSXresident_getPatches(&x)==0&&x.descriptorCount==1&&x.slotCount==2);epoch=x.descriptor[0].descriptor.epoch;MSXresident_clearPatches();OK(MSXresident_observePipe(1,ids,p,2,1)==0&&MSXresident_getPatches(&x)==0&&x.descriptorCount==0&&x.slotCount==0);OK(MSXresident_stageReverse(1)==0&&MSXresident_getPatches(&x)==0&&x.descriptorCount==1&&x.slotCount==0&&x.descriptor[0].descriptor.epoch==epoch+1&&x.descriptor[0].descriptor.head==s1&&x.descriptor[0].descriptor.tail==s0);OK(MSXresident_getSlotForParcel(1,11,&s0,&g0)==0&&MSXresident_getSlotForParcel(1,22,&s1,&g1)==0&&s0==0&&s1==1&&g0==1&&g1==1);MSXresident_clearPatches();m=payload(c,l,2,11);m.hstep=91;OK(MSXresident_stageMeta(1,s0,g0,&m)==0&&MSXresident_getPatches(&x)==0&&x.slotCount==1&&x.slot[0].kind==MSX_RESIDENT_PATCH_META&&x.slot[0].payload.c[1]==1);MSXresident_clearPatches();OK(MSXresident_stageRemove(1,s1,g1)==0&&MSXresident_getPatches(&x)==0&&x.descriptorCount==1&&x.slotCount==1&&x.slot[0].kind==MSX_RESIDENT_PATCH_INVALIDATE&&x.slot[0].used==0);MSXresident_clearPatches();m=payload(c,l,4,33);OK(MSXresident_stageInsert(1,0,&m,&s1,&g1)==0&&g1==2);m.hstep=93;OK(MSXresident_stageMeta(1,s1,g1,&m)==0&&MSXresident_getPatches(&x)==0&&x.slotCount==1&&x.slot[0].kind==MSX_RESIDENT_PATCH_IMPORT);OK(MSXresident_stageRemove(1,s1,g1)==0);OK(MSXresident_getPatches(&x)==0&&x.descriptorCount==1&&x.slotCount==1&&x.slot[0].slot==s1&&x.slot[0].generation==2&&x.slot[0].kind==MSX_RESIDENT_PATCH_INVALIDATE&&x.slot[0].used==0);MSXresident_clearPatches();OK(MSXresident_getPatches(&x)==0&&x.descriptorCount==0&&x.slotCount==0);q=payload(c,l,5,11);q.hstep=92;OK(MSXresident_stageMeta(1,s0,g0,&q)==0&&MSXresident_getPatches(&x)==0&&x.slotCount==1);}
/* 7: stale result rejects before copy. */
static void t7(void){char b[512];double c[2]={0,1},l[2]={0,2};uint64_t id=10;MSXResidentPayload p=payload(c,l,2,id),q;MSXResidentHandoffPlan plan;MSXResidentHandoffResult r;setup(1,1);onecsv(b,sizeof(b),UP,2);open1(b);OK(MSXresident_observePipe(1,&id,&p,1,1)==0);OK(MSXresident_planHandoff(1,2,1,0,0,1,&plan)==0&&plan.itemCount==1);OK(MSXresident_getSlotPayload(1,0,1,&q)==0);memset(&r,0,sizeof(r));r.linkIndex=1;r.slot=plan.item[0].slot;r.generation=plan.item[0].generation;r.pipeEpoch=plan.pipeEpoch;r.payload=q;OK(MSXresident_observePipe(1,&id,&p,1,-1)==0);OK(MSXresident_applyHandoff(&r,1)==MSX_RESIDENT_ERR_GENERATION);}
/* Selected fetch identity is a stable (slot,generation,parcel,epoch) tuple.
   Removing a row advances the descriptor epoch and generation reuse cannot
   make an old selected result appear valid. */
static void t19(void){char b[512];double c[2]={0,1},l[2]={0,2};uint64_t id=10,newid=20;uint32_t gen,slot,newgen;uint64_t parcel,epoch;MSXResidentPayload p=payload(c,l,2,id),q;MSXResidentPatchBatch x;setup(1,1);onecsv(b,sizeof(b),UP,2);open1(b);OK(MSXresident_observePipe(1,&id,&p,1,1)==0);OK(MSXresident_getSlotIdentity(1,0,&gen,&parcel,&epoch)==0&&gen==1&&parcel==id);OK(MSXresident_stageRemove(1,0,gen)==0&&MSXresident_getSlotIdentity(1,0,&gen,&parcel,&epoch)==MSX_RESIDENT_ERR_GENERATION);OK(MSXresident_getPatches(&x)==0&&x.slotCount==1&&x.slot[0].kind==MSX_RESIDENT_PATCH_INVALIDATE&&x.slot[0].payload.c==NULL&&x.slot[0].payload.lastc==NULL);MSXresident_clearPatches();p.parcelId=newid;OK(MSXresident_stageInsert(1,0,&p,&slot,&newgen)==0&&slot==0&&newgen==2);OK(MSXresident_getSlotIdentity(1,0,&gen,&parcel,&epoch)==0&&gen==2&&parcel==newid);OK(MSXresident_getSlotPayload(1,0,1,&q)==MSX_RESIDENT_ERR_GENERATION&&MSXresident_getSlotPayload(1,0,2,&q)==0&&q.parcelId==newid);}
/* 20: post-transport demote commits endpoint rows as one prevalidated batch.
   An interior/stale request must fail before any row, epoch, or patch changes;
   the valid head+tail request then commits both rows and one descriptor patch.
   This is the CPU contract used by the production demote transaction after
   selected GPU fetch has returned parcel identities. */
static void t20(void){char b[512];double c[2]={0,1},l[2]={0,2};uint64_t ids[4]={10,20,30,40},parcel,epoch0,epoch1;uint32_t g0,g1,g2,g3;MSXResidentPayload p[4],q;MSXResidentHandoffItem bad[2],good[2];MSXResidentPatchBatch x;setup(1,1);onecsv(b,sizeof(b),UP,4);open1(b);p[0]=payload(c,l,2,10);p[1]=payload(c,l,3,20);p[2]=payload(c,l,4,30);p[3]=payload(c,l,5,40);OK(MSXresident_observePipe(1,ids,p,4,1)==0);OK(MSXresident_getSlotIdentity(1,0,&g0,&parcel,&epoch0)==0&&parcel==10);OK(MSXresident_getSlotIdentity(1,1,&g1,&parcel,&epoch1)==0&&parcel==20&&epoch1==epoch0);OK(MSXresident_getSlotIdentity(1,2,&g2,&parcel,&epoch1)==0&&parcel==30&&epoch1==epoch0);OK(MSXresident_getSlotIdentity(1,3,&g3,&parcel,&epoch1)==0&&parcel==40&&epoch1==epoch0);bad[0]=(MSXResidentHandoffItem){1,0,g0,0,epoch0+1,0};bad[1]=(MSXResidentHandoffItem){1,2,g2,0,epoch0+1,0};OK(MSXresident_validateRemoveBatch(1,bad,2)==MSX_RESIDENT_ERR_GENERATION);OK(MSXresident_getSlotIdentity(1,0,&g0,&parcel,&epoch1)==0&&parcel==10&&epoch1==epoch0);bad[0].pipeEpoch=epoch0;bad[1].pipeEpoch=epoch0;OK(MSXresident_validateRemoveBatch(1,bad,2)==MSX_RESIDENT_ERR_ARGUMENT);OK(MSXresident_getSlotIdentity(1,0,&g0,&parcel,&epoch1)==0&&parcel==10&&epoch1==epoch0);OK(MSXresident_getPatches(&x)==0&&x.descriptorCount==1&&x.slotCount==4);MSXresident_clearPatches();good[0]=(MSXResidentHandoffItem){1,0,g0,0,epoch0,0};good[1]=(MSXResidentHandoffItem){1,3,g3,1,epoch0,0};OK(MSXresident_validateRemoveBatch(1,good,2)==0&&MSXresident_stageRemoveBatch(1,good,2)==0);OK(MSXresident_getSlotIdentity(1,0,&g0,&parcel,&epoch1)==MSX_RESIDENT_ERR_GENERATION&&MSXresident_getSlotIdentity(1,3,&g3,&parcel,&epoch1)==MSX_RESIDENT_ERR_GENERATION);OK(MSXresident_getSlotPayload(1,1,1,&q)==0&&q.parcelId==20);OK(MSXresident_getPatches(&x)==0&&x.descriptorCount==1&&x.slotCount==2&&x.descriptor[0].descriptor.count==2&&x.descriptor[0].descriptor.epoch==epoch0+2);}
/* 21: an unexpected demote commit failure poisons the Resident runtime.  No
   later consumer may observe a plausible zero/CPU-mirror value. */
static void t21(void){char b[512];double c[2]={0,1},l[2]={0,2};uint64_t id=77,parcel,epoch;uint32_t generation;MSXResidentPayload p=payload(c,l,2,id),q;MSXResidentPatchBatch x;setup(1,1);onecsv(b,sizeof(b),UP,2);open1(b);OK(MSXresident_observePipe(1,&id,&p,1,1)==0);MSXresident_clearPatches();MSXresident_poison();OK(MSXresident_getSlotIdentity(1,0,&generation,&parcel,&epoch)==MSX_RESIDENT_ERR_POISONED);OK(MSXresident_getSlotPayload(1,0,1,&q)==MSX_RESIDENT_ERR_POISONED);OK(MSXresident_stageRemove(1,0,generation)==MSX_RESIDENT_ERR_POISONED);OK(MSXresident_getPatches(&x)==MSX_RESIDENT_OK&&x.descriptorCount==0&&x.slotCount==0);}
/* 22: callers validate every link before staging any link.  A later-link
   stale request therefore cannot leave an earlier link partially removed. */
static void t22(void){char b[768];double c[2]={0,1},l[2]={0,2};uint64_t a=101,z=202,parcel,epoch;uint32_t ga,gz;MSXResidentPayload pa=payload(c,l,2,a),pz=payload(c,l,3,z),q;MSXResidentHandoffItem good,bad;MSXResidentPatchBatch x;setup(1,2);snprintf(b,sizeof(b),"link_index,link_id,capacity,max_core_count,combined_burst_p99,guard,case_hash\n1,L1,2,2,1,2,%s\n2,L2,2,2,1,2,%s\n",UP,UP);csv("resident_phase2a.csv",b);OK(MSXresident_open("resident_phase2a.csv")==0);MSXresident_setMode(MSX_RESIDENT_SHADOW,0);OK(MSXresident_observePipe(1,&a,&pa,1,1)==0&&MSXresident_observePipe(2,&z,&pz,1,1)==0);OK(MSXresident_getSlotIdentity(1,0,&ga,&parcel,&epoch)==0&&parcel==a);OK(MSXresident_getSlotIdentity(2,0,&gz,&parcel,&epoch)==0&&parcel==z);MSXresident_clearPatches();good=(MSXResidentHandoffItem){1,0,ga,0,epoch,0};bad=(MSXResidentHandoffItem){2,0,gz,0,epoch+1,0};OK(MSXresident_validateRemoveBatch(1,&good,1)==0&&MSXresident_validateRemoveBatch(2,&bad,1)==MSX_RESIDENT_ERR_GENERATION);OK(MSXresident_getSlotIdentity(1,0,&ga,&parcel,&epoch)==0&&parcel==a);OK(MSXresident_getPatches(&x)==0&&x.descriptorCount==0&&x.slotCount==0);OK(MSXresident_stageRemoveBatch(1,&good,1)==0&&MSXresident_getSlotPayload(1,0,1,&q)==MSX_RESIDENT_ERR_GENERATION);}
/* 23: explicit audit poisoning reaches both CPU Resident rows and dense
   Hybrid Core views without changing volume or parcel identity. */
static void t23(void){Pseg core;MSXResidentPayload q;uint32_t slot,generation;uint64_t parcel;double volume; if(!fixture()){OK(0);return;}core=MSXsegStorage_hybridCoreSegFromHead(1,0);OK(core!=NULL&&MSXresident_getSlotIdentity(1,0,&generation,&parcel,NULL)==0);slot=0;volume=core?core->v:0.0;OK(MSXresident_auditPoisonCpuMirrors()==MSX_RESIDENT_OK);OK(MSXsegStorage_hybridAuditPoisonCoreMirrors()==0);OK(MSXresident_getSlotPayload(1,slot,generation,&q)==MSX_RESIDENT_OK&&isnan(q.c[1])&&isnan(q.lastc[1]));OK(core!=NULL&&isnan(core->c[1])&&isnan(core->lastc[1])&&core->hybridId==parcel&&core->v==volume);}
/* 24: A0 audit snapshots preserve CPU topology and expose complete row order
   plus the Core/Resident identity mapping without publishing any state. */
static void t24(void){MSXHybridAuditSnapshot s;MSXHybridAuditRow rows[8];uint32_t n=0;Pseg first,last;int count; if(!fixture()){OK(0);return;}first=MSX.FirstSeg[1];last=MSX.LastSeg[1];count=MSX.Link[1].nsegs;OK(MSXsegStorage_hybridAuditSnapshot(1,&s,rows,8,&n)==0);OK(n==5&&s.total==5&&s.core_count==1&&s.downstream_boundary==2&&s.upstream_boundary==2);OK(rows[0].core==0&&rows[1].core==0&&rows[2].core==1&&rows[3].core==0&&rows[4].core==0);OK(rows[2].resident_slot>=0&&rows[2].parcel_id==rows[2].segment->hybridId&&rows[2].generation>0);OK(MSXsegStorage_hybridAuditSnapshot(1,&s,NULL,0,&n)==0&&n==5);OK(MSX.FirstSeg[1]==first&&MSX.LastSeg[1]==last&&MSX.Link[1].nsegs==count);}
static Pseg fseg(double v,uint64_t id){double c[2]={0,1},l[2]={0,2};Pseg s=MSXqual_getFreeSeg(v,c);if(s){s->hybridId=id;memcpy(s->lastc,l,sizeof(l));}return s;}
static int fixture(void){Pseg prev=NULL;MSXResidentLayout l;int i,z;char b[512];setup(1,1);MSX.SegmentStorage=SEG_STORAGE_HYBRID;onecsv(b,sizeof(b),UP,16);csv("resident_phase2a.csv",b);z=MSXresident_open("resident_phase2a.csv");if(z){fprintf(stderr,"fixture: resident_open=%d\n",z);return 0;}MSXresident_setMode(MSX_RESIDENT_RESIDENT,1);z=MSXsegStorage_open();if(z){fprintf(stderr,"fixture: storage_open=%d\n",z);return 0;}z=MSXresident_getLayout(&l);if(z){fprintf(stderr,"fixture: get_layout=%d\n",z);return 0;}z=MSXsegStorage_hybridReserve(&l);if(z){fprintf(stderr,"fixture: hybrid_reserve=%d\n",z);return 0;}for(i=0;i<5;i++){Pseg s=fseg(i+1,100+i);if(!s){fprintf(stderr,"fixture: fseg[%d]\n",i);return 0;}s->next=prev;if(prev)prev->prev=s;else MSX.FirstSeg[1]=s;prev=s;MSX.LastSeg[1]=s;MSX.Link[1].nsegs++;}z=MSXsegStorage_hybridizeAll();if(z){fprintf(stderr,"fixture: hybridize_all=%d\n",z);return 0;}if(MSXsegStorage_hybridCoreCount(1)!=1){fprintf(stderr,"fixture: core_count=%d\n",MSXsegStorage_hybridCoreCount(1));return 0;}return 1;}
/* 18: active-row identity filtering is slot-exact and fail-closed. */
static void t18(void){Pseg prev=NULL,s;MSXResidentLayout l;char b[512];int i;uint64_t id;
 setup(1,1);MSX.SegmentStorage=SEG_STORAGE_HYBRID;onecsv(b,sizeof(b),UP,16);csv("resident_phase2a.csv",b);OK(MSXresident_open("resident_phase2a.csv")==0);MSXresident_setMode(MSX_RESIDENT_RESIDENT,1);OK(MSXsegStorage_open()==0&&MSXresident_getLayout(&l)==0&&MSXsegStorage_hybridReserve(&l)==0);
 for(i=0;i<6;i++){s=fseg(i+1,900+i);OK(s!=NULL);s->next=prev;if(prev)prev->prev=s;else MSX.FirstSeg[1]=s;prev=s;MSX.LastSeg[1]=s;MSX.Link[1].nsegs++;}
 OK(MSXsegStorage_hybridizeAll()==0&&MSXsegStorage_hybridCoreCount(1)==2);s=MSXsegStorage_hybridCoreSegFromHead(1,0);id=s?s->hybridId:0;
 OK(id!=0&&MSXsegStorage_isHybridCoreSlotIdentity(1,0,id));
 OK(!MSXsegStorage_isHybridCoreSlotIdentity(1,1,id)); /* other active row */
 OK(!MSXsegStorage_isHybridCoreSlotIdentity(1,0,id+1));
 OK(!MSXsegStorage_isHybridCoreSlotIdentity(1,2,id)); /* unused row */
 OK(!MSXsegStorage_isHybridCoreSlotIdentity(1,-1,id)&&!MSXsegStorage_isHybridCoreSlotIdentity(1,16,id));
}
/* Phase 3C startup is a two-phase transaction: staging has no linked-list
   writes; a simulated GPU failure aborts it, while the success commit is
   Resident-allocation-free. */
static int initialFixture(void){Pseg prev=NULL;MSXResidentLayout l;int i,z;char b[512];setup(1,1);MSX.SegmentStorage=SEG_STORAGE_HYBRID;onecsv(b,sizeof(b),UP,16);csv("resident_phase2a.csv",b);if(MSXresident_open("resident_phase2a.csv"))return 0;MSXresident_setMode(MSX_RESIDENT_RESIDENT,1);if(MSXsegStorage_open()||MSXresident_getLayout(&l)||MSXsegStorage_hybridReserve(&l))return 0;for(i=0;i<5;i++){Pseg s=fseg(i+1,100+i);if(!s)return 0;s->next=prev;if(prev)prev->prev=s;else MSX.FirstSeg[1]=s;prev=s;MSX.LastSeg[1]=s;MSX.Link[1].nsegs++;}z=MSXresident_beginInitialImage();return z==0;}
static void t14(void){Pseg first,last,mid;int n;MSXResidentPatchBatch b;uint64_t a;
 if(!initialFixture()){OK(0);return;}first=MSX.FirstSeg[1];last=MSX.LastSeg[1];mid=first->prev;n=MSX.Link[1].nsegs;
 OK(MSXsegStorage_hybridPrepareInitialImage()==0);OK(MSXsegStorage_hybridStageInitialImage()==0);OK(MSXresident_getInitialBatch(&b)==0&&b.descriptorCount==1&&b.descriptor[0].descriptor.count==1&&b.slotCount==16&&b.slot[0].used==1);
 /* Equivalent to any pre-commit GPU failure: all CPU topology is intact. */
 MSXsegStorage_hybridAbortInitialImage();MSXresident_abortInitialImage();
 OK(MSX.FirstSeg[1]==first&&MSX.LastSeg[1]==last&&MSX.Link[1].nsegs==n&&first->prev==mid&&mid->next==first&&MSXsegStorage_hybridCoreCount(1)==0);
 if(!initialFixture()){OK(0);return;}OK(MSXsegStorage_hybridPrepareInitialImage()==0&&MSXsegStorage_hybridStageInitialImage()==0);MSXresident_testResetAllocationCount();MSXresident_testFailAllocationAfter(0);a=MSXresident_testAllocationCount();OK(MSXsegStorage_hybridCommitInitialImage()==0&&MSXresident_commitInitialImage()==0);OK(MSXresident_testAllocationCount()==a&&MSXsegStorage_hybridCoreCount(1)==1&&MSX.Link[1].nsegs==5);MSXresident_testFailAllocationAfter(-1);}
static int txdata(MSXResidentHandoffPlan*p,MSXResidentHandoffResult*r){MSXResidentPayload q;if(MSXresident_planHandoff(1,2,1,0,0,1,p)||p->itemCount!=1)return 0;if(MSXresident_getSlotPayload(1,p->item[0].slot,p->item[0].generation,&q))return 0;memset(r,0,sizeof(*r));r->linkIndex=1;r->slot=p->item[0].slot;r->generation=p->item[0].generation;r->pipeEpoch=p->pipeEpoch;r->payload=q;return 1;}
/* 8: real materialize then abort. */
static void t8(void){MSXResidentHandoffPlan p;MSXResidentHandoffResult r;MSXResidentHandoffTransaction x={0};if(!fixture()){OK(0);return;}if(!txdata(&p,&r)){OK(0);return;}OK(MSXresident_prepareHandoffTransaction(&p,&r,1,&x)==0&&x.opaque);MSXresident_abortHandoffTransaction(&x);OK(!x.opaque&&MSXsegStorage_hybridCoreCount(1)==1);}
/* 9: real materialize validation and commit. */
static void t9(void){MSXResidentHandoffPlan p;MSXResidentHandoffResult r;MSXResidentHandoffTransaction x={0};MSXResidentPayload q;uint64_t a;if(!fixture()){OK(0);return;}if(!txdata(&p,&r)){OK(0);return;}OK(MSXresident_prepareHandoffTransaction(&p,&r,1,&x)==0);OK(MSXresident_validateHandoffTransactions(&x,1)==0);MSXresident_testResetAllocationCount();a=MSXresident_testAllocationCount();MSXresident_commitHandoffTransaction(&x);OK(MSXresident_testAllocationCount()==a&&!x.opaque);OK(MSXsegStorage_hybridCoreCount(1)==0&&MSX.Link[1].nsegs==5);OK(MSXresident_getSlotPayload(1,r.slot,r.generation,&q)==MSX_RESIDENT_ERR_GENERATION);}
/* 10: malformed transaction data fails closed. */
static void t10(void){MSXResidentHandoffPlan p;MSXResidentHandoffResult r;MSXResidentHandoffTransaction x={0};if(!fixture()){OK(0);return;}if(!txdata(&p,&r)){OK(0);return;}r.payload.lastc=NULL;OK(MSXresident_prepareHandoffTransaction(&p,&r,1,&x)==MSX_RESIDENT_ERR_ARGUMENT&&!x.opaque);}
/* 10b: prepare/validate/abort consume only the preHybrid arenas.  The module
   allocation seam remains armed, so any new steady-state core allocation
   turns this into a deterministic failure. */
static void t10b(void){int n;MSXResidentHandoffPlan p;MSXResidentHandoffResult r;MSXResidentHandoffTransaction x={0};MSXResidentPayload q;uint64_t id;
 for(n=0;n<6;n++){uint64_t a;if(!fixture()){OK(0);MSXresident_testFailAllocationAfter(-1);return;}if(!txdata(&p,&r)){OK(0);MSXresident_testFailAllocationAfter(-1);return;}MSXresident_testResetAllocationCount();MSXresident_testFailAllocationAfter(n);a=MSXresident_testAllocationCount();OK(MSXresident_prepareHandoffTransaction(&p,&r,1,&x)==0&&x.opaque);OK(MSXresident_testAllocationCount()==a);OK(MSXresident_validateHandoffTransactions(&x,1)==0&&MSXresident_testAllocationCount()==a);MSXresident_abortHandoffTransaction(&x);OK(!x.opaque&&MSXresident_testAllocationCount()==a&&MSXsegStorage_hybridCoreCount(1)==1&&MSX.Link[1].nsegs==5);MSXresident_testFailAllocationAfter(-1);}
 if(!fixture()){OK(0);return;}if(!txdata(&p,&r)){OK(0);return;}OK(MSXresident_prepareHandoffTransaction(&p,&r,1,&x)==0);OK(MSXresident_getSlotPayload(1,r.slot,r.generation,&q)==0);id=q.parcelId;OK(MSXresident_observePipe(1,&id,&q,1,-1)==0);OK(MSXresident_validateHandoffTransactions(&x,1)==MSX_RESIDENT_ERR_GENERATION);MSXresident_abortHandoffTransaction(&x);OK(!x.opaque&&MSXsegStorage_hybridCoreCount(1)==1&&MSX.Link[1].nsegs==5);}
/* 11: raw-byte SHA-256 and Phase 3A pure configuration matrix. */
static void t11(void){char h[65],a[65],b[65],csvbuf[512];MSXResidentConfig c;setup(1,1);
 csv("resident_inp.inp","abc");csv("resident_case.msx","[OPTIONS]\r\nSOLVER ROS2\r\n");
 OK(MSXresident_sha256File("resident_inp.inp",h)&&!strcmp(h,"ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"));
 OK(MSXresident_caseHashFiles("resident_inp.inp","resident_case.msx",a));csv("resident_case.msx","[OPTIONS]\nSOLVER ROS2\n");OK(MSXresident_caseHashFiles("resident_inp.inp","resident_case.msx",b)&&strcmp(a,b));
 snprintf(csvbuf,sizeof(csvbuf),"link_index,link_id,capacity,max_core_count,combined_burst_p99,guard,case_hash\n1,L1,4,2,1,2,%s\n",b);csv("resident_config.csv",csvbuf);
 memset(&c,0,sizeof(c));c.mode=MSX_RESIDENT_OFF;OK(MSXresident_validateConfig(&c)==MSX_RESIDENT_OK);
 c.mode=MSX_RESIDENT_SHADOW;c.guard=2;c.segmentStorage=SEG_STORAGE_HYBRID;c.solver=ROS2;c.gpuSolver=ROS2;c.gpuReact=c.gpuOde=c.gpuEquil=c.gpuFormula=1;c.capacityFile="resident_config.csv";c.caseHash=b;OK(MSXresident_validateConfig(&c)==MSX_RESIDENT_OK);
 c.mode=MSX_RESIDENT_RESIDENT;OK(MSXresident_validateConfig(&c)==MSX_RESIDENT_OK);c.guard=1;OK(MSXresident_validateConfig(&c)==MSX_RESIDENT_ERR_GUARD);c.guard=2;c.segmentStorage=SEG_STORAGE_PSEG;OK(MSXresident_validateConfig(&c)==MSX_RESIDENT_ERR_CONFIG);c.segmentStorage=SEG_STORAGE_HYBRID;c.solver=EUL;OK(MSXresident_validateConfig(&c)==MSX_RESIDENT_ERR_SOLVER);c.solver=ROS2;c.gpuScope=GPU_FULL_REACT;OK(MSXresident_validateConfig(&c)==MSX_RESIDENT_ERR_SCOPE);c.gpuScope=GPU_PIPE_SEGMENT;c.hasWall=1;OK(MSXresident_validateConfig(&c)==MSX_RESIDENT_ERR_UNSUPPORTED_WALL);c.hasWall=0;c.hasDispersion=1;OK(MSXresident_validateConfig(&c)==MSX_RESIDENT_ERR_UNSUPPORTED_DISPERSION);c.hasDispersion=0;c.caseHash="ABCDEFABCDEFABCDEFABCDEFABCDEFABCDEFABCDEFABCDEFABCDEFABCDEFABCD";OK(MSXresident_validateConfig(&c)==MSX_RESIDENT_ERR_CSV);c.capacityFile="missing.csv";OK(MSXresident_validateConfig(&c)==MSX_RESIDENT_ERR_PATH);
 remove("resident_inp.inp");remove("resident_case.msx");remove("resident_config.csv");}
/* 12: fixed capacity is preflighted before any Pseg promotion. */
static void t12(void){Pseg prev=NULL,first,last;MSXResidentLayout l;char b[512];int i,n;setup(1,1);MSX.SegmentStorage=SEG_STORAGE_HYBRID;onecsv(b,sizeof(b),UP,1);csv("resident_phase2a.csv",b);OK(MSXresident_open("resident_phase2a.csv")==0);MSXresident_setMode(MSX_RESIDENT_RESIDENT,1);OK(MSXsegStorage_open()==0&&MSXresident_getLayout(&l)==0&&MSXsegStorage_hybridReserve(&l)==0);OK(MSXsegStorage_hybridCoreCapacity(1)==1);for(i=0;i<6;i++){Pseg s=fseg(i+1,200+i);OK(s!=NULL);s->next=prev;if(prev)prev->prev=s;else MSX.FirstSeg[1]=s;prev=s;MSX.LastSeg[1]=s;MSX.Link[1].nsegs++;}first=MSX.FirstSeg[1];last=MSX.LastSeg[1];n=MSX.Link[1].nsegs;OK(MSXsegStorage_hybridizeAll()==ERR_PIPE_RING_CAPACITY);OK(MSX.FirstSeg[1]==first&&MSX.LastSeg[1]==last&&MSX.Link[1].nsegs==n&&MSXsegStorage_hybridCoreCount(1)==0);}
/* 13: the all-link final validation accepts distinct fixed arenas at once. */
static void t13(void){char b[768];MSXResidentLayout l;MSXResidentHandoffPlan p[3];MSXResidentHandoffItem item[3];MSXResidentHandoffResult r[3];MSXResidentHandoffTransaction x[3]={{0}};uint64_t a,segCalls;int k,i;setup(1,2);MSX.SegmentStorage=SEG_STORAGE_HYBRID;snprintf(b,sizeof(b),"link_index,link_id,capacity,max_core_count,combined_burst_p99,guard,case_hash\n1,L1,16,16,1,2,%s\n2,L2,16,16,1,2,%s\n",UP,UP);csv("resident_phase2a.csv",b);OK(MSXresident_open("resident_phase2a.csv")==0);MSXresident_setMode(MSX_RESIDENT_RESIDENT,1);OK(MSXsegStorage_open()==0&&MSXresident_getLayout(&l)==0&&MSXsegStorage_hybridReserve(&l)==0);for(k=1;k<=2;k++){Pseg prev=NULL;for(i=0;i<5;i++){Pseg s=fseg(i+1,(uint64_t)(100*k+i));OK(s!=NULL);s->next=prev;if(prev)prev->prev=s;else MSX.FirstSeg[k]=s;prev=s;MSX.LastSeg[k]=s;MSX.Link[k].nsegs++;}}OK(MSXsegStorage_hybridizeAll()==0&&MSXsegStorage_hybridCoreCount(1)==1&&MSXsegStorage_hybridCoreCount(2)==1);memset(p,0,sizeof(p));memset(r,0,sizeof(r));for(k=1;k<=2;k++){MSXResidentPayload q;OK(MSXresident_planHandoffInto((uint32_t)k,2,1,0,0,1,&item[k],1,&p[k])==0&&p[k].itemCount==1);OK(MSXresident_getSlotPayload((uint32_t)k,p[k].item[0].slot,p[k].item[0].generation,&q)==0);r[k].linkIndex=(uint32_t)k;r[k].slot=p[k].item[0].slot;r[k].generation=p[k].item[0].generation;r[k].boundarySide=p[k].boundarySide;r[k].pipeEpoch=p[k].pipeEpoch;r[k].payload=q;}MSXresident_testResetAllocationCount();MSXresident_testFailAllocationAfter(0);segmentAllocCalls=0;segmentAllocFail=1;MSX.FreeSeg=NULL;a=MSXresident_testAllocationCount();segCalls=segmentAllocCalls;OK(MSXresident_prepareHandoffTransaction(&p[1],&r[1],1,&x[1])==0&&MSXresident_prepareHandoffTransaction(&p[2],&r[2],1,&x[2])==0);OK(MSXresident_validateHandoffTransactions(x,3)==0&&MSXresident_testAllocationCount()==a&&segmentAllocCalls==segCalls);MSXresident_abortHandoffTransaction(&x[1]);MSXresident_abortHandoffTransaction(&x[2]);memset(x,0,sizeof(x));OK(MSXresident_prepareHandoffTransaction(&p[1],&r[1],1,&x[1])==0&&MSXresident_prepareHandoffTransaction(&p[2],&r[2],1,&x[2])==0);OK(MSXresident_validateHandoffTransactions(x,3)==0&&segmentAllocCalls==segCalls);MSXresident_abortHandoffTransaction(&x[1]);MSXresident_abortHandoffTransaction(&x[2]);segmentAllocFail=0;MSXresident_testFailAllocationAfter(-1);}
/* 15: legacy HYBRID with Resident OFF keeps dynamic capacity. */
static void t15(void){Pseg prev=NULL;int i;setup(1,1);MSX.SegmentStorage=SEG_STORAGE_HYBRID;OK(MSXsegStorage_open()==0);for(i=0;i<5;i++){Pseg s=fseg(i+1,400+i);OK(s!=NULL);s->next=prev;if(prev)prev->prev=s;else MSX.FirstSeg[1]=s;prev=s;MSX.LastSeg[1]=s;MSX.Link[1].nsegs++;}OK(MSXsegStorage_hybridizeAll()==0);OK(MSXsegStorage_hybridCoreCount(1)==1&&MSX.Link[1].nsegs==5);}
/* 16: a later-link initial validation failure cannot partially commit link 1. */
static void t16(void){char b[768];MSXResidentLayout l;Pseg first1,last1,first2;int n1,k,i;setup(1,2);MSX.SegmentStorage=SEG_STORAGE_HYBRID;snprintf(b,sizeof(b),"link_index,link_id,capacity,max_core_count,combined_burst_p99,guard,case_hash\n1,L1,16,16,1,2,%s\n2,L2,16,16,1,2,%s\n",UP,UP);csv("resident_phase2a.csv",b);OK(MSXresident_open("resident_phase2a.csv")==0);MSXresident_setMode(MSX_RESIDENT_RESIDENT,1);OK(MSXsegStorage_open()==0&&MSXresident_getLayout(&l)==0&&MSXsegStorage_hybridReserve(&l)==0);for(k=1;k<=2;k++){Pseg prev=NULL;for(i=0;i<5;i++){Pseg s=fseg(i+1,(uint64_t)(500*k+i));OK(s!=NULL);s->next=prev;if(prev)prev->prev=s;else MSX.FirstSeg[k]=s;prev=s;MSX.LastSeg[k]=s;MSX.Link[k].nsegs++;}}OK(MSXresident_beginInitialImage()==0&&MSXsegStorage_hybridPrepareInitialImage()==0&&MSXsegStorage_hybridStageInitialImage()==0);first1=MSX.FirstSeg[1];last1=MSX.LastSeg[1];n1=MSX.Link[1].nsegs;first2=MSX.FirstSeg[2];MSX.FirstSeg[2]=first2->prev;OK(MSXsegStorage_hybridCommitInitialImage()==ERR_PIPE_RING_CAPACITY);OK(MSX.FirstSeg[1]==first1&&MSX.LastSeg[1]==last1&&MSX.Link[1].nsegs==n1&&MSXsegStorage_hybridCoreCount(1)==0);MSX.FirstSeg[2]=first2;MSXsegStorage_hybridAbortInitialImage();MSXresident_abortInitialImage();}
/* 17: mixed CSV guards must survive open/layout/reserve.  Equal-length
   pipes have different Core counts, and the staged descriptors publish that
   exact per-link image before any CPU topology mutation. */
static void t17(void){char b[768];MSXResidentLayout l;MSXResidentPatchBatch x;int k,i;setup(1,2);MSX.SegmentStorage=SEG_STORAGE_HYBRID;
 snprintf(b,sizeof(b),"link_index,link_id,capacity,max_core_count,combined_burst_p99,guard,case_hash\n1,L1,16,16,1,2,%s\n2,L2,16,16,1,4,%s\n",UP,UP);csv("resident_phase2a.csv",b);
 OK(MSXresident_open("resident_phase2a.csv")==0&&MSXresident_getLayout(&l)==0&&l.guard&&l.guard[1]==2&&l.guard[2]==4);MSXresident_setMode(MSX_RESIDENT_RESIDENT,1);
 OK(MSXsegStorage_open()==0&&MSXsegStorage_hybridReserve(&l)==0);
 for(k=1;k<=2;k++){Pseg prev=NULL;for(i=0;i<9;i++){Pseg s=fseg(i+1,(uint64_t)(700*k+i));OK(s!=NULL);s->next=prev;if(prev)prev->prev=s;else MSX.FirstSeg[k]=s;prev=s;MSX.LastSeg[k]=s;MSX.Link[k].nsegs++;}}
 OK(MSXresident_beginInitialImage()==0&&MSXsegStorage_hybridPrepareInitialImage()==0&&MSXsegStorage_hybridStageInitialImage()==0);
 OK(MSXresident_getInitialBatch(&x)==0&&x.descriptorCount==2&&x.descriptor[0].linkIndex==1&&x.descriptor[0].descriptor.count==5&&x.descriptor[1].linkIndex==2&&x.descriptor[1].descriptor.count==1);
 OK(MSXsegStorage_hybridCommitInitialImage()==0&&MSXresident_commitInitialImage()==0&&MSXsegStorage_hybridCoreCount(1)==5&&MSXsegStorage_hybridCoreCount(2)==1);
 }
/* 25: the A1 snapshot contract uses the canonical all-downstream shape when
   a pipe has no Core.  This is also the reference form used by audit checks
   after a batch demote removes the last Core row. */
static void t25(void){char b[512];MSXResidentLayout l;MSXHybridAuditSnapshot s,z;MSXHybridAuditRow rows[8],again[8];uint32_t n=0,m=0;Pseg prev=NULL,first,last;int i,nsegs,core,orient;setup(1,1);MSX.SegmentStorage=SEG_STORAGE_HYBRID;onecsv(b,sizeof(b),UP,16);csv("resident_phase2a.csv",b);OK(MSXresident_open("resident_phase2a.csv")==0);MSXresident_setMode(MSX_RESIDENT_RESIDENT,1);OK(MSXsegStorage_open()==0&&MSXresident_getLayout(&l)==0&&MSXsegStorage_hybridReserve(&l)==0);for(i=0;i<4;i++){Pseg q=fseg(i+1,(uint64_t)(1200+i));OK(q!=NULL);q->next=prev;if(prev)prev->prev=q;else MSX.FirstSeg[1]=q;prev=q;MSX.LastSeg[1]=q;MSX.Link[1].nsegs++;}OK(MSXsegStorage_hybridizeAll()==0);first=MSX.FirstSeg[1];last=MSX.LastSeg[1];nsegs=MSX.Link[1].nsegs;core=MSXsegStorage_hybridCoreCount(1);orient=MSXsegStorage_hybridOrientation(1);OK(MSXsegStorage_hybridAuditSnapshot(1,&s,rows,8,&n)==0&&n==4&&s.link_index==1&&s.total==4&&s.core_count==0&&s.downstream_boundary==4&&s.upstream_boundary==0&&s.first_core_slot==-1&&s.last_core_slot==-1&&s.orient==orient);for(i=0;i<4;i++)OK(rows[i].parcel_id==(uint64_t)(1200+i)&&rows[i].core==0&&rows[i].core_slot==-1&&rows[i].resident_slot==-1&&rows[i].generation==0&&rows[i].pipe_epoch==0&&rows[i].segment!=NULL);OK(MSXsegStorage_hybridAuditSnapshot(1,&z,again,8,&m)==0&&m==n&&z.link_index==s.link_index&&z.total==s.total&&z.core_count==s.core_count&&z.downstream_boundary==s.downstream_boundary&&z.upstream_boundary==s.upstream_boundary&&z.first_core_slot==s.first_core_slot&&z.last_core_slot==s.last_core_slot&&z.orient==s.orient);for(i=0;i<4;i++)OK(again[i].parcel_id==rows[i].parcel_id&&again[i].core==rows[i].core&&again[i].core_slot==rows[i].core_slot&&again[i].resident_slot==rows[i].resident_slot&&again[i].generation==rows[i].generation&&again[i].pipe_epoch==rows[i].pipe_epoch&&again[i].segment==rows[i].segment);OK(MSX.FirstSeg[1]==first&&MSX.LastSeg[1]==last&&MSX.Link[1].nsegs==nsegs&&MSXsegStorage_hybridCoreCount(1)==core&&MSXsegStorage_hybridOrientation(1)==orient);}
/* 26: close diagnostics are silent unless detail diagnostics or an explicit
   audit requested them.  The production close path supplies the two inputs;
   this pure predicate keeps the regression independent of stderr capture. */
static void t26(void){OK(!MSXresidentRuntime_diagnosticSummaryGate(0,0));OK(MSXresidentRuntime_diagnosticSummaryGate(1,0));OK(MSXresidentRuntime_diagnosticSummaryGate(0,1));OK(MSXresidentRuntime_diagnosticSummaryGate(1,1));}
int main(void){t1();t2();t3();t4();t5();t6();t6a();t6b();t6c();t6d();t6e();t7();t19();t20();t21();t22();t23();t24();t8();t9();t10();t10b();t11();t12();t13();t14();t15();t16();t17();t18();t25();t26();cleanup();remove("resident_phase2a.csv");printf("assertions_passed=%d\nassertions_failed=%d\n",pass,fail);return fail?1:0;}
