/* Phase 2b CUDA-core contract harness: production .cu, no stub or simulation. */
#include <stdio.h>
#include <string.h>
#include <math.h>
#include <stdint.h>
#include <cuda_runtime_api.h>
#include "msxresident_core_cuda.h"

static int pass, fail, aggregateQueries, aggregateHits, aggregateRebuilds;
#define OK(x) do { if (x) ++pass; else { ++fail; fprintf(stderr,"FAIL:%d: %s\n",__LINE__,#x); } } while (0)
void MSXgpu_profileRecordAggregate(uint64_t q,uint64_t h,uint64_t r) { aggregateQueries+=(int)q; aggregateHits+=(int)h; aggregateRebuilds+=(int)r; }
#define S 3
#define LARGE 2048
static void desc(MSXResidentDescriptorPatch *d,uint32_t link,uint32_t cap,uint32_t count,uint64_t epoch,int orient) { memset(d,0,sizeof(*d)); d->linkIndex=link; d->descriptor.linkIndex=link; d->descriptor.capacity=cap; d->descriptor.count=count; d->descriptor.head=count?0:UINT32_MAX; d->descriptor.tail=count?count-1:UINT32_MAX; d->descriptor.epoch=epoch; d->descriptor.orient=orient; }
static void slot(MSXResidentSlotPatch *x,uint32_t link,uint32_t local,uint32_t gen,uint64_t id,double v,double base) { static double c[4][S],l[4][S]; uint32_t q=(local+(link-1)*2)&3; memset(x,0,sizeof(*x)); c[q][0]=base;c[q][1]=base+1;c[q][2]=base+2;l[q][0]=base+10;l[q][1]=base+11;l[q][2]=base+12; x->linkIndex=link;x->slot=local;x->generation=gen;x->used=1;x->payload.parcelId=id;x->payload.volume=v;x->payload.hstep=base+3;x->payload.hresponse=base+4;x->payload.uresponse=base+5;x->payload.dresponse=base+6;x->payload.c=c[q];x->payload.lastc=l[q]; }
static MSXResidentGpu *open4(void) { uint32_t cap[3]={0,2,2},base[3]={0,0,2}; MSXResidentGpuOpen o={2,4,S,cap,base}; MSXResidentGpu*g=0; OK(MSXresidentGpu_open(&o,&g)==0&&g); return g; }
static MSXResidentGpu *initial4(void) { MSXResidentGpu*g=open4(); MSXResidentDescriptorPatch d[2]; MSXResidentSlotPatch x[4]; MSXResidentPatchBatch b; desc(&d[0],1,2,2,5,1);desc(&d[1],2,2,2,7,-1);slot(&x[0],1,0,1,101,2,10);slot(&x[1],1,1,1,102,3,20);slot(&x[2],2,0,1,201,4,30);slot(&x[3],2,1,1,202,5,40);b=(MSXResidentPatchBatch){d,2,x,4};OK(MSXresidentGpu_initialUpload(g,&b)==0);MSXresidentGpu_setDiagnosticMode(g,1);return g; }
static int snap(MSXResidentGpu*g,MSXResidentGpuReduction*r,double*m) { return MSXresidentGpu_reduce(g,m,S,r)==0; }
static int same(const MSXResidentGpuReduction*a,const MSXResidentGpuReduction*b,const double*x,const double*y) { return a->activeCount==b->activeCount&&a->checksumXor==b->checksumXor&&a->checksumSum==b->checksumSum&&a->activeVolume==b->activeVolume&&!memcmp(x,y,sizeof(double)*S); }
static void invalid_unchanged(MSXResidentGpu*g,MSXResidentPatchBatch*b,MSXResidentStatus want) { MSXResidentGpuReduction a,z;double x[S],y[S];OK(snap(g,&a,x));OK(MSXresidentGpu_applyPatches(g,b)==want);OK(snap(g,&z,y)&&same(&a,&z,x,y)); }
static void t_open(void) { uint32_t c[3]={0,2,2},b[3]={0,0,4};MSXResidentGpuOpen o={2,6,S,c,b};MSXResidentGpu*g=0; OK(MSXresidentGpu_open(&o,&g)==0);MSXresidentGpu_close(g);g=0;b[2]=1;OK(MSXresidentGpu_open(&o,&g)<0);b[2]=4;c[2]=3;OK(MSXresidentGpu_open(&o,&g)<0); {uint32_t zc[2]={0,1},zb[2]={0,0};MSXResidentGpuOpen z={1,1,S,zc,zb};MSXResidentDescriptorPatch d;MSXResidentSlotPatch x;MSXResidentPatchBatch q;desc(&d,1,1,0,1,1);memset(&x,0,sizeof(x));x.linkIndex=1;x.slot=0;x.generation=1;q=(MSXResidentPatchBatch){&d,1,&x,1};OK(MSXresidentGpu_open(&z,&g)==0&&MSXresidentGpu_initialUpload(g,&q)==0);MSXresidentGpu_close(g);} }
static void t_initial(void) { MSXResidentGpu*g=open4();MSXResidentDescriptorPatch d[2];MSXResidentSlotPatch x[4];MSXResidentPatchBatch b;desc(&d[0],1,2,2,5,1);desc(&d[1],2,2,2,7,-1);slot(&x[0],1,0,1,1,1,1);slot(&x[1],1,1,1,2,1,2);slot(&x[2],2,0,1,3,1,3);slot(&x[3],2,1,1,4,1,4);b=(MSXResidentPatchBatch){d,2,x,4};OK(MSXresidentGpu_initialUpload(g,&b)==0);OK(MSXresidentGpu_initialUpload(g,&b)<0);MSXresidentGpu_close(g); g=open4();b.descriptorCount=1;OK(MSXresidentGpu_initialUpload(g,&b)<0);b.descriptorCount=2;b.slotCount=3;OK(MSXresidentGpu_initialUpload(g,&b)<0);b.slotCount=4;x[3].slot=0;OK(MSXresidentGpu_initialUpload(g,&b)<0);x[3].slot=1;b.slotCount=3;OK(MSXresidentGpu_initialUpload(g,&b)<0);MSXresidentGpu_close(g); }
static void t_scatter(void) { MSXResidentGpu*g=initial4();MSXResidentDescriptorPatch d;MSXResidentSlotPatch x[2];MSXResidentPatchBatch b;MSXResidentHandoffItem it[2];MSXResidentHandoffPlan p;MSXResidentHandoffResult r[2];double c[8],l[8];MSXResidentGpuFetchOutput out={r,c,l,4};desc(&d,2,2,2,8,-1);slot(&x[0],2,1,2,222,9,70);slot(&x[1],2,0,2,211,8,60);b=(MSXResidentPatchBatch){&d,1,x,2};OK(MSXresidentGpu_applyPatches(g,&b)==0);memset(it,0,sizeof(it));it[0]=(MSXResidentHandoffItem){2,1,2,0,8,0};it[1]=(MSXResidentHandoffItem){2,0,2,0,8,0};p=(MSXResidentHandoffPlan){2,0,2,8,0,it};OK(MSXresidentGpu_fetchHandoffs(g,&p,&out,2)==0&&r[0].payload.parcelId==222&&r[1].payload.parcelId==211&&c[0]==70&&c[4]==60&&r[0].payload.hstep==73);MSXresidentGpu_close(g); }
static void t_descriptor_generation(void) { MSXResidentGpu*g=initial4();MSXResidentDescriptorPatch d;MSXResidentPatchBatch b;desc(&d,1,2,2,6,0);b=(MSXResidentPatchBatch){&d,1,0,0};invalid_unchanged(g,&b,MSX_RESIDENT_ERR_ARGUMENT);desc(&d,1,2,2,4,1);invalid_unchanged(g,&b,MSX_RESIDENT_ERR_GENERATION);desc(&d,1,2,3,6,1);invalid_unchanged(g,&b,MSX_RESIDENT_ERR_ARGUMENT); {MSXResidentSlotPatch x;desc(&d,1,2,2,6,1);slot(&x,1,0,2,301,2,50);b=(MSXResidentPatchBatch){&d,1,&x,1};OK(MSXresidentGpu_applyPatches(g,&b)==0);x.generation=1;invalid_unchanged(g,&b,MSX_RESIDENT_ERR_GENERATION);} MSXresidentGpu_close(g); }
static void t_fetch(void) { MSXResidentGpu*g=initial4();MSXResidentHandoffItem a[2],b[1];MSXResidentHandoffPlan p;MSXResidentHandoffResult r[2];double c[8],l[8];MSXResidentGpuFetchOutput o={r,c,l,4};memset(a,0,sizeof(a));a[0]=(MSXResidentHandoffItem){1,1,1,0,5,0};a[1]=(MSXResidentHandoffItem){1,0,1,0,5,0};p=(MSXResidentHandoffPlan){1,0,2,5,0,a};OK(MSXresidentGpu_fetchHandoffs(g,&p,&o,2)==0&&r[0].payload.parcelId==102&&r[1].payload.parcelId==101&&c[0]==20&&c[4]==10);c[0]=777;o.stride=2;OK(MSXresidentGpu_fetchHandoffs(g,&p,&o,2)<0&&c[0]==777);o.stride=4;o.cOut=0;OK(MSXresidentGpu_fetchHandoffs(g,&p,&o,2)<0);o.cOut=c;b[0]=(MSXResidentHandoffItem){2,0,1,0,7,0};p=(MSXResidentHandoffPlan){2,0,1,7,0,b};OK(MSXresidentGpu_fetchHandoffs(g,&p,&o,1)==0&&r[0].payload.parcelId==201);b[0].generation=9;OK(MSXresidentGpu_fetchHandoffs(g,&p,&o,1)==MSX_RESIDENT_ERR_GENERATION);b[0].generation=1;b[0].pipeEpoch=6;p.pipeEpoch=6;OK(MSXresidentGpu_fetchHandoffs(g,&p,&o,1)==MSX_RESIDENT_ERR_GENERATION); {MSXResidentGpuReduction z;double m[S];OK(snap(g,&z,m)&&z.fetchStale>=1&&z.epochStale>=1);}MSXresidentGpu_close(g); }
/* A selected demote batch is a flat multi-link gather: one staging H2D and
   exactly three D2H APIs (metadata, c, lastc), independent of row count.
   The counters are API calls, not logical handoff rows. */
static void t_fetch_batch_contract(void) { MSXResidentGpu*g=initial4();MSXResidentHandoffItem a[2];MSXResidentHandoffResult r[2];MSXResidentGpuFetchOutput o;MSXResidentGpuTransferStats before,after;double c[8]={0},l[8]={0};a[0]=(MSXResidentHandoffItem){1,0,1,0,5,0};a[1]=(MSXResidentHandoffItem){2,1,1,0,7,1};o=(MSXResidentGpuFetchOutput){r,c,l,4};OK(MSXresidentGpu_getTransferStats(g,&before)==0&&before.h2dCalls==0&&before.d2hCalls==0);OK(MSXresidentGpu_fetchHandoffBatch(g,a,2,&o)==0&&r[0].payload.parcelId==101&&r[1].payload.parcelId==202&&c[0]==10&&c[4]==40);OK(MSXresidentGpu_getTransferStats(g,&after)==0&&after.h2dCalls==1&&after.d2hCalls==3&&after.h2dBytes>0&&after.d2hBytes>0);a[1].pipeEpoch=8;OK(MSXresidentGpu_fetchHandoffBatch(g,a,2,&o)==MSX_RESIDENT_ERR_GENERATION);OK(MSXresidentGpu_getTransferStats(g,&before)==0&&before.h2dCalls==after.h2dCalls&&before.d2hCalls==after.d2hCalls);a[1].pipeEpoch=7;a[1].linkIndex=1;a[1].slot=0;OK(MSXresidentGpu_fetchHandoffBatch(g,a,2,&o)==MSX_RESIDENT_ERR_ARGUMENT);OK(MSXresidentGpu_getTransferStats(g,&before)==0&&before.h2dCalls==after.h2dCalls&&before.d2hCalls==after.d2hCalls);MSXresidentGpu_close(g); }
static void t_reduce_lifecycle(void) { MSXResidentGpu*g=initial4();MSXResidentGpuReduction a,b;double x[S],y[S],hyd[MSX_RESIDENT_HYD_STRIDE]={0},changed[S]={123,21,22};aggregateQueries=aggregateHits=aggregateRebuilds=0;OK(snap(g,&a,x)&&a.activeCount==4&&a.activeVolume==14&&x[0]==(10*2+20*3+30*4+40*5));OK(snap(g,&b,y)&&same(&a,&b,x,y)); {MSXResidentActiveItem ai={1,0,1,5,2,hyd};MSXResidentActiveBatch ab={&ai,1};MSXResidentGpuDeviceView v;MSXResidentGpuReactResult rr;OK(MSXresidentGpu_prepareActive(g,&ab,&v,&rr)==0&&cudaMemcpy((void*)(uintptr_t)v.c,changed,sizeof(changed),cudaMemcpyHostToDevice)==cudaSuccess&&MSXresidentGpu_finishActive(g,&rr)==0&&snap(g,&a,x)&&x[0]==(123*2+20*3+30*4+40*5));} {MSXResidentDescriptorPatch d;MSXResidentSlotPatch q;MSXResidentPatchBatch z;desc(&d,1,2,2,6,1);slot(&q,1,0,2,101,2,NAN);((double*)q.payload.c)[1]=1;((double*)q.payload.c)[2]=2;z=(MSXResidentPatchBatch){&d,1,&q,1};OK(MSXresidentGpu_applyPatches(g,&z)==0&&snap(g,&a,x)&&a.nanCount==1&&a.errorCount==1&&a.firstErrorSlot==0);slot(&q,1,1,2,102,3,INFINITY);((double*)q.payload.c)[1]=1;((double*)q.payload.c)[2]=2;OK(MSXresidentGpu_applyPatches(g,&z)==0&&snap(g,&a,x)&&a.infCount==1&&a.nanCount==1&&a.errorCount==2&&a.firstErrorSlot==0);}OK(aggregateQueries==5&&aggregateHits==1&&aggregateRebuilds==4);MSXresidentGpu_close(g);MSXresidentGpu_close(0);for(int i=0;i<3;i++){g=open4();MSXresidentGpu_close(g);} }
static void t_hole_initial_fetch(void) { uint32_t cap[3]={0,2,2},base[3]={0,0,4};MSXResidentGpuOpen o={2,6,S,cap,base};MSXResidentGpu*g=0;MSXResidentDescriptorPatch d[2];MSXResidentSlotPatch x[4];MSXResidentPatchBatch q;MSXResidentGpuReduction z;double m[S],c[S],l[S];MSXResidentHandoffItem i={2,0,1,0,7,0};MSXResidentHandoffPlan p={2,0,1,7,0,&i};MSXResidentHandoffResult r;MSXResidentGpuFetchOutput out={&r,c,l,S};desc(&d[0],1,2,2,5,1);desc(&d[1],2,2,2,7,1);slot(&x[0],1,0,1,101,2,10);slot(&x[1],1,1,1,102,3,20);slot(&x[2],2,0,1,201,4,30);slot(&x[3],2,1,1,202,5,40);q=(MSXResidentPatchBatch){d,2,x,4};OK(MSXresidentGpu_open(&o,&g)==0&&MSXresidentGpu_initialUpload(g,&q)==0);OK(snap(g,&z,m)&&z.activeCount==4&&z.activeVolume==14);OK(MSXresidentGpu_fetchHandoffs(g,&p,&out,1)==0&&r.payload.parcelId==201&&c[0]==30&&l[2]==42);MSXresidentGpu_close(g); }
static void t_ring_span_reject(void) { uint32_t cap[2]={0,3},base[2]={0,0};MSXResidentGpuOpen o={1,3,S,cap,base};MSXResidentGpu*g=0;MSXResidentDescriptorPatch d;MSXResidentSlotPatch x[3],off;MSXResidentPatchBatch q,b;desc(&d,1,3,3,1,1);slot(&x[0],1,0,1,1,1,1);slot(&x[1],1,1,1,2,1,2);slot(&x[2],1,2,1,3,1,3);q=(MSXResidentPatchBatch){&d,1,x,3};OK(MSXresidentGpu_open(&o,&g)==0&&MSXresidentGpu_initialUpload(g,&q)==0);desc(&d,1,3,2,2,1);d.descriptor.tail=2;memset(&off,0,sizeof(off));off.linkIndex=1;off.slot=1;off.generation=2;off.used=0;b=(MSXResidentPatchBatch){&d,1,&off,1};invalid_unchanged(g,&b,MSX_RESIDENT_ERR_ARGUMENT);MSXresidentGpu_close(g); }
static void t_wrap_active(void) { uint32_t cap[2]={0,4},base[2]={0,0};MSXResidentGpuOpen o={1,4,S,cap,base};MSXResidentGpu*g=0;MSXResidentDescriptorPatch d;MSXResidentSlotPatch x[4];MSXResidentPatchBatch q;double hyd[MSX_RESIDENT_HYD_STRIDE]={0};MSXResidentActiveItem a[2];MSXResidentActiveBatch b;MSXResidentGpuDeviceView v;MSXResidentGpuReactResult r;desc(&d,1,4,2,5,-1);d.descriptor.tail=3;slot(&x[0],1,0,1,101,1,1);memset(&x[1],0,sizeof(x[1]));x[1].linkIndex=1;x[1].slot=1;memset(&x[2],0,sizeof(x[2]));x[2].linkIndex=1;x[2].slot=2;slot(&x[3],1,3,1,102,1,2);q=(MSXResidentPatchBatch){&d,1,x,4};a[0]=(MSXResidentActiveItem){1,0,1,5,1,hyd};a[1]=(MSXResidentActiveItem){1,3,1,5,1,hyd};b=(MSXResidentActiveBatch){a,2};OK(MSXresidentGpu_open(&o,&g)==0&&MSXresidentGpu_initialUpload(g,&q)==0);OK(MSXresidentGpu_prepareActive(g,&b,&v,&r)==0&&v.itemCount==2&&v.hydStride==MSX_RESIDENT_HYD_STRIDE);OK(MSXresidentGpu_finishActive(g,&r)==0);MSXresidentGpu_close(g); }
static void t_active_view(void) { MSXResidentGpu*g=initial4(); double hyd[MSX_RESIDENT_HYD_STRIDE]={0},h; uint32_t u; MSXResidentActiveItem a={1,0,1,5,2.0,hyd}, dup[2]={{1,0,1,5,2.0,hyd},{1,0,1,5,2.0,hyd}}, stale={1,0,9,5,2.0,hyd}; MSXResidentActiveBatch b={&a,1}, d={dup,2}, z={&stale,1}; MSXResidentGpuDeviceView v,w; MSXResidentGpuReactResult r; OK(MSXresidentGpu_prepareActive(g,&b,&v,&r)==0&&v.itemCount==1&&v.segRow&&v.c&&v.lastc&&v.hyd&&v.ros2Err&&v.hydStride==MSX_RESIDENT_HYD_STRIDE); OK(MSXresidentGpu_getDeviceView(g,&w)==0&&w.hstep==v.hstep&&w.hydStride==MSX_RESIDENT_HYD_STRIDE); h=91.25;u=11;OK(cudaMemcpy((void*)(uintptr_t)v.hstep,&h,sizeof(h),cudaMemcpyHostToDevice)==cudaSuccess);OK(cudaMemcpy((void*)(uintptr_t)v.ros2LastHstep,&h,sizeof(h),cudaMemcpyHostToDevice)==cudaSuccess);OK(cudaMemcpy((void*)(uintptr_t)v.ros2Nfcn,&u,sizeof(u),cudaMemcpyHostToDevice)==cudaSuccess);u=12;OK(cudaMemcpy((void*)(uintptr_t)v.ros2Njac,&u,sizeof(u),cudaMemcpyHostToDevice)==cudaSuccess);u=13;OK(cudaMemcpy((void*)(uintptr_t)v.ros2Naccept,&u,sizeof(u),cudaMemcpyHostToDevice)==cudaSuccess);u=14;OK(cudaMemcpy((void*)(uintptr_t)v.ros2Nreject,&u,sizeof(u),cudaMemcpyHostToDevice)==cudaSuccess);OK(MSXresidentGpu_finishActive(g,&r)==0&&r.ros2Nfcn==11&&r.ros2Njac==12&&r.ros2Naccept==13&&r.ros2Nreject==14&&r.ros2LastHstep==91.25); OK(MSXresidentGpu_prepareActive(g,&b,&v,&r)==0);OK(cudaMemcpy(&h,(void*)(uintptr_t)v.hstep,sizeof(h),cudaMemcpyDeviceToHost)==cudaSuccess&&h==91.25);OK(MSXresidentGpu_finishActive(g,&r)==0); OK(MSXresidentGpu_prepareActive(g,&d,&v,&r)==MSX_RESIDENT_ERR_ARGUMENT); OK(MSXresidentGpu_prepareActive(g,&z,&v,&r)==MSX_RESIDENT_ERR_GENERATION); MSXresidentGpu_close(g); }
static void t_active_error(void) { MSXResidentGpu*g=initial4();double hyd[MSX_RESIDENT_HYD_STRIDE]={0};int e=-2;MSXResidentActiveItem a={1,0,1,5,2,hyd};MSXResidentActiveBatch b={&a,1};MSXResidentGpuDeviceView v;MSXResidentGpuReactResult r;OK(MSXresidentGpu_prepareActive(g,&b,&v,&r)==0);OK(cudaMemcpy((void*)(uintptr_t)v.ros2Err,&e,sizeof(e),cudaMemcpyHostToDevice)==cudaSuccess);OK(MSXresidentGpu_finishActive(g,&r)==MSX_RESIDENT_ERR_GPU&&r.ros2Error==-2);OK(MSXresidentGpu_prepareActive(g,&b,&v,&r)==MSX_RESIDENT_ERR_POISONED);MSXresidentGpu_close(g);}
static void t_large_batch(void) { static MSXResidentSlotPatch x[LARGE]; static MSXResidentActiveItem a[LARGE]; static MSXResidentHandoffItem hi[LARGE]; static MSXResidentHandoffResult hr[LARGE]; static double hc[(size_t)LARGE*S],hl[(size_t)LARGE*S]; MSXResidentDescriptorPatch d,dd[2]; MSXResidentPatchBatch b; MSXResidentGpu*g=0; MSXResidentGpuDeviceView v; MSXResidentGpuReactResult r; MSXResidentGpuReduction z; MSXResidentGpuFetchOutput fo; MSXResidentGpuTransferStats ts0,ts1; double m[S],hyd[MSX_RESIDENT_HYD_STRIDE]={0}; uint32_t cap[2]={0,LARGE},base[2]={0,0}; MSXResidentGpuOpen o={1,LARGE,S,cap,base}; for(uint32_t i=0;i<LARGE;i++){slot(&x[i],1,i,1,1000+i,1.0,(double)i);a[i]=(MSXResidentActiveItem){1,i,1,1,1.0,hyd};hi[i]=(MSXResidentHandoffItem){1,i,1,0,1};}desc(&d,1,LARGE,LARGE,1,1);b=(MSXResidentPatchBatch){&d,1,x,LARGE};OK(MSXresidentGpu_open(&o,&g)==0&&MSXresidentGpu_initialUpload(g,&b)==0);fo=(MSXResidentGpuFetchOutput){hr,hc,hl,S};OK(MSXresidentGpu_getTransferStats(g,&ts0)==0&&ts0.h2dCalls==0&&ts0.d2hCalls==0);OK(MSXresidentGpu_fetchHandoffBatch(g,hi,LARGE,&fo)==0&&hr[LARGE-1].payload.parcelId==1000+LARGE-1);OK(MSXresidentGpu_getTransferStats(g,&ts1)==0&&ts1.h2dCalls==1&&ts1.d2hCalls==3&&ts1.h2dBytes>0&&ts1.d2hBytes>0);OK(snap(g,&z,m)&&z.activeCount==LARGE);dd[0]=d;dd[1]=d;b=(MSXResidentPatchBatch){dd,2,0,0};invalid_unchanged(g,&b,MSX_RESIDENT_ERR_ARGUMENT);b=(MSXResidentPatchBatch){0,0,x,1};x[0].slot=LARGE;invalid_unchanged(g,&b,MSX_RESIDENT_ERR_CAPACITY);x[0].slot=0;{MSXResidentActiveBatch q={a,LARGE};OK(MSXresidentGpu_prepareActive(g,&q,&v,&r)==0&&v.itemCount==LARGE&&v.hydStride==MSX_RESIDENT_HYD_STRIDE);OK(MSXresidentGpu_finishActive(g,&r)==0);}MSXresidentGpu_close(g);}
/* P1 typed patches: META leaves the GPU concentration vectors untouched,
   INVALIDATE carries no concentration payload, and a later IMPORT reuses the
   slot with a new generation.  The descriptor patch is intentionally sparse. */
static void t_typed_patches(void) { MSXResidentGpu*g=initial4();MSXResidentGpuReduction a,z;MSXResidentDescriptorPatch d,multi[2];MSXResidentSlotPatch x,typed[2];MSXResidentPatchBatch b;double m[S],n[S];slot(&x,1,0,1,101,2,90);x.kind=MSX_RESIDENT_PATCH_META;x.payload.c=0;x.payload.lastc=0;b=(MSXResidentPatchBatch){0,0,&x,1};OK(snap(g,&a,m)&&MSXresidentGpu_applyPatches(g,&b)==0&&snap(g,&z,n)&&same(&a,&z,m,n));desc(&d,1,2,1,6,1);d.descriptor.head=1;d.descriptor.tail=1;memset(&x,0,sizeof(x));x.linkIndex=1;x.slot=0;x.generation=1;x.used=0;x.kind=MSX_RESIDENT_PATCH_INVALIDATE;x.payload.c=0;x.payload.lastc=0;b=(MSXResidentPatchBatch){&d,1,&x,1};OK(MSXresidentGpu_applyPatches(g,&b)==0&&snap(g,&z,n)&&z.activeCount==3);slot(&x,1,0,2,301,2,55);x.kind=MSX_RESIDENT_PATCH_IMPORT;desc(&d,1,2,2,7,1);b=(MSXResidentPatchBatch){&d,1,&x,1};OK(MSXresidentGpu_applyPatches(g,&b)==0&&snap(g,&z,n)&&z.activeCount==4);
/* One sparse batch may carry multiple descriptors and mixed typed events.  META
   must preserve both GPU payloads; INVALIDATE carries no concentration arrays. */
desc(&multi[0],1,2,2,8,1);desc(&multi[1],2,2,2,8,-1);slot(&typed[0],1,1,1,102,3,20);typed[0].kind=MSX_RESIDENT_PATCH_META;slot(&typed[1],2,0,1,201,4,30);typed[1].kind=MSX_RESIDENT_PATCH_META;b=(MSXResidentPatchBatch){multi,2,typed,2};OK(snap(g,&a,m)&&MSXresidentGpu_applyPatches(g,&b)==0&&snap(g,&z,n)&&same(&a,&z,m,n));desc(&multi[0],1,2,2,9,1);desc(&multi[1],2,2,1,9,-1);multi[1].descriptor.head=1;multi[1].descriptor.tail=1;slot(&typed[0],1,1,1,102,3,20);typed[0].kind=MSX_RESIDENT_PATCH_META;memset(&typed[1],0,sizeof(typed[1]));typed[1].linkIndex=2;typed[1].slot=0;typed[1].generation=1;typed[1].kind=MSX_RESIDENT_PATCH_INVALIDATE;b=(MSXResidentPatchBatch){multi,2,typed,2};OK(MSXresidentGpu_applyPatches(g,&b)==0&&snap(g,&z,n)&&z.activeCount==3);MSXresidentGpu_close(g);}
static void t_active_sync(void) { MSXResidentGpu*g=initial4();MSXResidentGpuReduction z;double mass[S],hyd[MSX_RESIDENT_HYD_STRIDE]={0},c[S],l[S],h=77;MSXResidentActiveItem a={1,0,1,5,2,hyd};MSXResidentActiveBatch b={&a,1};MSXResidentGpuDeviceView v;MSXResidentGpuReactResult r;MSXResidentGpuActiveSyncRow row;MSXResidentGpuActiveSyncOutput o={&row,c,l,S};MSXResidentDescriptorPatch d;MSXResidentPatchBatch q;OK(MSXresidentGpu_prepareActive(g,&b,&v,&r)==0);c[0]=321;l[0]=654;OK(cudaMemcpy((void*)(uintptr_t)v.c,c,sizeof(c),cudaMemcpyHostToDevice)==cudaSuccess);OK(cudaMemcpy((void*)(uintptr_t)v.lastc,l,sizeof(l),cudaMemcpyHostToDevice)==cudaSuccess);OK(cudaMemcpy((void*)(uintptr_t)v.hstep,&h,sizeof(h),cudaMemcpyHostToDevice)==cudaSuccess);OK(MSXresidentGpu_finishActive(g,&r)==0);OK(MSXresidentGpu_reduce(g,mass,S,&z)==0&&mass[0]==321*2+20*3+30*4+40*5);memset(c,0,sizeof(c));memset(l,0,sizeof(l));OK(MSXresidentGpu_syncActive(g,&o,1)==0&&row.linkIndex==1&&row.globalRow==0&&row.generation==1&&row.descriptorEpoch==5&&row.hstep==77&&c[0]==321&&l[0]==654);OK(MSXresidentGpu_prepareActive(g,&b,&v,&r)==0&&MSXresidentGpu_finishActive(g,&r)==0);desc(&d,1,2,2,6,1);q=(MSXResidentPatchBatch){&d,1,0,0};OK(MSXresidentGpu_applyPatches(g,&q)==0);OK(MSXresidentGpu_syncActive(g,&o,1)==MSX_RESIDENT_ERR_GENERATION);MSXresidentGpu_close(g);}
int main(void) { struct cudaDeviceProp p;int n=0;cudaError_t e=cudaGetDeviceCount(&n);printf("cuda_required=true\n");if(e!=cudaSuccess||n<1){printf("gpu_name=unavailable\nassertions_passed=0\nassertions_failed=1\n");return 2;}cudaGetDeviceProperties(&p,0);printf("gpu_name=%s\n",p.name);OK(MSXresidentGpu_isEnabled()==1);t_open();t_initial();t_scatter();t_descriptor_generation();t_fetch();t_fetch_batch_contract();t_reduce_lifecycle();t_hole_initial_fetch();t_ring_span_reject();t_wrap_active();t_active_view();t_active_sync();t_active_error();t_large_batch();t_typed_patches();printf("assertions_passed=%d\nassertions_failed=%d\n",pass,fail);return fail?1:0; }
